<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated;

use Automattic\WooCommerce\Internal\DependencyManagement\AbstractServiceProvider;

use Automattic\WooCommerce\Api\Webhooks;

class ApiClassesServiceProvider extends AbstractServiceProvider {

	/**
	 * The classes/interfaces that are serviced by this service provider.
	 *
	 * @var array
	 */
	protected $provides = array(
		Webhooks::class,
	);

	/**
	 * Register the classes.
	 */
	public function register() {
		foreach ( $this->provides as $class_name ) {
			$this->share_with_auto_arguments( $class_name );
		}
	}
}
