<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;

class CreateWebhookInputType extends InputObjectType {
    public function __construct() {
        $config = array(
            'name'         => 'CreateWebhookInput',
            'description'  => __('Data for a new webhook.', 'woocommerce'),
            'fields'       => $this->get_fields(),
            'interfaces' => [
                GraphQLController::resolve_type('WebhookDefinition')
            ],
            'parseValue' => fn($values) => GraphQLController::parse_input_value('CreateWebhookInput', $values)
            //TODO: parseValue with properties being arrays and other objects
        );

        parent::__construct($config);
    }

    private function get_fields() {
        $fields = [
            'user_id' => [
                'description' => 'Webhook user id.',
                'type' =>Type::nonNull(Type::int())
            ],
            'status' => [
                'description' => 'Webhook status.',
                'type' =>Type::nonNull(GraphQLController::resolve_type('WebhookStatus'))
            ],
        ];

        $fields = array_merge($fields, GraphQLController::resolve_type('WebhookDefinition')->get_fields());

        return $fields;
    }
}