<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

class UserType extends ObjectType {
	public function __construct() {
		$config = array(
			'name'         => 'User',
			'description'  => __('A user.', 'woocommerce'),
			'fields'       => $this->get_fields(),
		);

		parent::__construct($config);
	}

	private function get_fields() {
		return [
			'id' => [
				'description' => 'User id',
				'type' =>Type::nonNull(Type::int())
			],
			'login' => [
				'description' => 'User login',
				'type' =>Type::nonNull(Type::string())
			],
			'email' => [
				'description' => 'User email',
				'type' =>Type::nonNull(Type::string()),
                'args' => [
                    'bar' => Type::nonNull(Type::int())
                ],
			],
		];
	}
}
