<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use GraphQL\Type\Definition\EnumType;

class WebhookStatusType extends EnumType {
	public function __construct() {
		$config = [
			'name' => 'WebhookStatus',
			'description' => 'Webhook status.',
			'values' => [
				'ACTIVE' => [
					'value' => 'active'
				],
				'PAUSED' => [
					'value' => 'paused'
				],
				'DISABLED' => [
					'value' => 'disabled'
				]
			]
		];

		parent::__construct($config);
	}
}
