<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use Automattic\WooCommerce\Internal\Api\GraphQL\GraphQLController;
use GraphQL\Type\Definition\InterfaceType;
use GraphQL\Type\Definition\Type;

class WebhookDefinitionType extends InterfaceType {
	public function __construct() {
		$config = array(
			'name'         => 'WebhookDefinition',
			'description'  => __('A webhook definition.', 'woocommerce'),
			'fields'       => $this->get_fields(),
		);

		parent::__construct($config);
	}

	public function get_fields() {
		return [
			'name' => [
				'description' => 'Webhook name.',
				'type' =>Type::nonNull(Type::string())
			],
			'topic' => [
				'description' => 'Webhook topic.',
				'type' =>Type::nonNull(Type::string())
			],
			'delivery_url' => [
				'description' => 'Webhook delivery URL.',
				'type' =>Type::nonNull(Type::string())
			],
			'secret' => [
				'description' => 'Webhook secret.',
				'type' =>Type::string()
			],
			'api_version' => [
				'description' => 'Webhook API version.',
				'type' =>Type::nonNull(GraphQLController::resolve_type('WebhookApiVersion'))
			],
		];
	}
}
