<?php

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes;

use GraphQL\Type\Definition\EnumType;

class WebhookApiVersionType extends EnumType {
	public function __construct() {
		$config = [
			'name' => 'WebhookApiType',
			'description' => 'Webhook API type.',
			'values' => [
				'API_V1' => [
					'value' => 'wp_api_v1'
				],
				'API_V2' => [
					'value' => 'wp_api_v2'
				],
				'API_V3' => [
					'value' => 'wp_api_v4'
				],
				'LEGACY_V3' => [
					'value' => 'legacy_v3'
				],
			]
		];

		parent::__construct($config);
	}
}
